# This workflow will publish a python package on pypi, when a release is created

name: release

on:
  release:
    types: [published]

permissions:
  # This permission is required for trusted publishing.
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry poetry-dynamic-versioning

    - name: Build package
      run: |
        poetry build

    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      ################################
      # REMOVE CUSTOM REPOSITORY TO  #
      # PUBLISH ON OFFICIAL PYPI     #
      ################################
      with:
        repository-url: https://test.pypi.org/legacy/
